name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check userscript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run project checks
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File tool/check.ps1
